### ISSUE TITLE
About Casper_note Economically finalized problem

### ISSUE THREAD

**Issue by AYEE0525** [changwu-tw/tester#1]
我參考了你的筆記，對於economically finalized定義你說:
"一個區塊、一個狀態或是一段歷史，會被認為已成定局。假設在同個高度上，存在一個證明可以用於懲罰造假或有誤的另一方，並課以 X 等量的罰金，這個 X 值，被稱作加密經濟的邊際安全 (Cryptoeconomic Security Margin)。"

然後我參考另一篇文章，他是說:
"如果一個客戶能夠證明(i) 區塊B1永遠會是這個規範鏈條的一部分，或者證明(ii) 導致區塊B1被恢復的參與者們一定會被保證受到等額X美元的懲罰，那麼這個區塊B1在經濟是被最終確定的，在密碼經濟安全的邊際是X美元。"

然後原文是說:
"A block B1 is economically finalized, with cryptoeconomic security margin $X, if a client has proof that either (i) B1 is going to be part of the canonical chain forever, or (ii) those actors that caused B1 to get reverted are guaranteed to be economically penalized by an amount equal to at least $X."

依照原文的解釋第一點我有懂，但第二點我一直不懂，第二點你的說法是:
"假設在同個高度上，存在一個證明可以用於懲罰造假或有誤的另一方，並課以 X 等量的罰金"
而我理解原文的意思是:
"導致B1回復的那些行為者保證在經濟上受到等於至少$ X的懲罰。"

你的解釋我看得懂，但好像跟原文不太一樣，但原文我怎麼翻譯都無法理解作者的意思，甚麼叫做" caused B1 to get reverted"? 是說如果B1最後沒有finalized就要被逞罰嗎?

然後我對逞罰還是不太理解，除了COMMIT_REQ 、PREPARE_REQ 、PREPARE_COMMIT_CONSISTENCY、NO_DBL_PREPARE四個條件會逞罰外，是不是我只要prepare投錯checkpoint就要受罰呢?

謝謝

**Comment by changwu-tw** [comment]
過去還在學習, 原文翻得有點力力辣辣

先解釋 block finalized, 一個區塊要被最終確認, 必須取得 2/3 以上的票 (2/3 的推導補在下方), 既然有 2/3 以上的共識認定, 基本上已成定局. 

原文這邊說, 如果 B1 被確認, 那麼就存在經濟安全邊際 $X, 則是來自存在一群驗證人 (validator), 他們可以對 B1 進行投票, 但這裡的票並非一人一票, 而是依照他的保證金數量成比例的權重. (vote by weight)

EX: 存在五個驗證人 ABCDE, 保證金分別是 10, 10, 10, 10, 60
那麼, 每人的票在這的比例分別是, 1:1:1:1:6

而如果 DE, 認為 B1 是合法的且投票, 那麼 B1 隱含著有 0.7 的保證金數量壓在他之上, 且應該被最終確認; 但是這時候, 出現了另一個 B1', 而且他得到的票有 0.8, 那就必須仲裁了. 因為這件事本身不合理, 不該有人同時把票投給兩個不同的區塊.

這時候, 肯定有人投了兩次票, 先假設有兩個區塊都分別得到 2/3 得票數, 代表了其中有 1/3 的人, 重複投了兩次票. 依據 capser 的 slashing 規則, 他的押金會被銷毀, 所以本來的數量剩 (1-1/3)=2/3, 原有的保證金有 1/3 被銷毀. 這時候, 利用重新計算得到的數量, 按照票數比例再去計算, 最後依舊選超過 2/3 的區塊為最終區塊.

在這個例子中, $X = 1/3(deposits), 也就是所謂的至少 $X 會被懲罰

把原文簡單修飾過, 如果一個區塊已經被確認, 要推翻這個共識, 至少會有 $X 的錢被懲罰. 原因是因為要推翻共識, 就會違規, 如上例.

**Comment by changwu-tw** [comment]
# Finality Threshold

1. 拜占庭節點: `F`
2. 誠實節點: `N-F`
3. 共識：至少 `T` 個節點同意

這個運作必須確保 Safety 以及 Liveness

## 1. Safety

即使有 F 個節點存在，都不應該影響系統安全

假設 `N-F` 個誠實節點因為某種原因分裂
則 `(N-F) / 2`

但協定必須確保分裂後，若 `F` 個拜占庭節點介入決策，不會影響安全
則 `(N-F) / 2 + F < T`

## 2. Liveness

確認系統可以持續保持運行，不會因不足的票數影響到決策，或使系統卡住
則 `N-F >= T`

## 同時滿足兩個條件

1. `(N-F) / 2 + F < T`
2. `N-F >= T`

## 整理後

`N-F > (N-F) / 2 + F`
—> `(N-F) / 2 > F`
—> `N-F > 2F`
—> `N > 3F`
—> `F < (1/3)N`

**Comment by AYEE0525** [comment]
哇賽！回好快，我以為要等兩三天耶，超級大感謝～～你真用心餒，解釋的很詳細，我是blockchain超級初學者，剛學兩個禮拜，如果我問了什麼爛爛的問題請見諒QQ
我再看看跟吸收一些知識，如果還是不懂再請教你吧,謝謝～～

changwu <notifications@github.com> 於 2018年3月11日 週日 下午11:24 寫道：
